FROM golang:alpine as builder

RUN mkdir build

ADD . /build/

WORKDIR /build
 
RUN go build -o main.

##stage 2 

FROM alpine

RUN adduser

COPY ./app

COPY --from=builder /build/main

WORKDIR /app

EXPOSE 3000

CMDp-"./main"
 